// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/unifiedui/agent-service",
            "email": "support@unifiedui.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/agent-service/health": {
            "get": {
                "description": "Returns the overall health status and component statuses",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Service healthy",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "Service unhealthy",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/agent-service/live": {
            "get": {
                "description": "Returns 200 if the service is alive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "Service alive",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/agent-service/ready": {
            "get": {
                "description": "Returns 200 if the service is ready to accept traffic",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "Service ready",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service not ready",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/agent-service/tenants/{tenantId}/autonomous-agents/{agentId}/traces": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Called by autonomous agents to report their trace data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Traces"
                ],
                "summary": "Update traces",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Trace updates",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateTracesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateTracesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/agent-service/tenants/{tenantId}/conversation/messages": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves messages for a conversation with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Get messages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Conversation ID",
                        "name": "conversationId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 50,
                        "description": "Maximum number of messages",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GetMessagesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends a message to an AI agent and returns the response via SSE streaming",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Send a message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Message content with applicationId",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/agent-service/tenants/{tenantId}/conversation/messages/{messageId}/traces": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all traces associated with a specific message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Traces"
                ],
                "summary": "Get message traces",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenantId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Message ID",
                        "name": "messageId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Conversation ID",
                        "name": "conversationId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GetMessageTracesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handlers.GetMessageTracesResponse": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                },
                "traces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Trace"
                    }
                }
            }
        },
        "handlers.GetMessagesResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Message"
                    }
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handlers.HealthResponse": {
            "type": "object",
            "properties": {
                "components": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handlers.InvokeConfig": {
            "type": "object",
            "properties": {
                "chatHistoryMessageCount": {
                    "type": "integer"
                }
            }
        },
        "handlers.MessageContent": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "content": {
                    "type": "string",
                    "maxLength": 32000,
                    "minLength": 1
                }
            }
        },
        "handlers.SendMessageRequest": {
            "type": "object",
            "required": [
                "applicationId",
                "message"
            ],
            "properties": {
                "applicationId": {
                    "type": "string"
                },
                "conversationId": {
                    "type": "string"
                },
                "invokeConfig": {
                    "$ref": "#/definitions/handlers.InvokeConfig"
                },
                "message": {
                    "$ref": "#/definitions/handlers.MessageContent"
                }
            }
        },
        "handlers.SendMessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/models.Message"
                }
            }
        },
        "handlers.TraceUpdate": {
            "type": "object",
            "required": [
                "conversationId",
                "messageId",
                "name",
                "status",
                "traceId",
                "type"
            ],
            "properties": {
                "conversationId": {
                    "type": "string"
                },
                "durationMs": {
                    "type": "integer"
                },
                "endedAt": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "input": {},
                "messageId": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/models.TraceMetadata"
                },
                "name": {
                    "type": "string"
                },
                "output": {},
                "parentTraceId": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "traceId": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "handlers.UpdateTracesRequest": {
            "type": "object",
            "required": [
                "traces"
            ],
            "properties": {
                "traces": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/handlers.TraceUpdate"
                    }
                }
            }
        },
        "handlers.UpdateTracesResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "integer"
                },
                "updated": {
                    "type": "integer"
                }
            }
        },
        "models.Message": {
            "type": "object",
            "properties": {
                "agentId": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "conversationId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/models.Metadata"
                },
                "role": {
                    "$ref": "#/definitions/models.MessageRole"
                },
                "tenantId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "models.MessageRole": {
            "type": "string",
            "enum": [
                "user",
                "assistant",
                "system"
            ],
            "x-enum-varnames": [
                "RoleUser",
                "RoleAssistant",
                "RoleSystem"
            ]
        },
        "models.Metadata": {
            "type": "object",
            "properties": {
                "agentType": {
                    "description": "AgentType is the type of agent that processed the message.",
                    "type": "string"
                },
                "custom": {
                    "description": "Custom holds additional custom metadata.",
                    "type": "object",
                    "additionalProperties": true
                },
                "latencyMs": {
                    "description": "Latency is the response latency in milliseconds.",
                    "type": "integer"
                },
                "model": {
                    "description": "Model is the model used for generating the response.",
                    "type": "string"
                },
                "tokensInput": {
                    "description": "TokensInput is the number of input tokens.",
                    "type": "integer"
                },
                "tokensOutput": {
                    "description": "TokensOutput is the number of output tokens.",
                    "type": "integer"
                }
            }
        },
        "models.Trace": {
            "type": "object",
            "properties": {
                "agentId": {
                    "type": "string"
                },
                "conversationId": {
                    "type": "string"
                },
                "durationMs": {
                    "type": "integer"
                },
                "endedAt": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "input": {},
                "messageId": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/models.TraceMetadata"
                },
                "name": {
                    "type": "string"
                },
                "output": {},
                "parentTraceId": {
                    "type": "string"
                },
                "startedAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/models.TraceStatus"
                },
                "tenantId": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/models.TraceType"
                }
            }
        },
        "models.TraceMetadata": {
            "type": "object",
            "properties": {
                "custom": {
                    "description": "Custom holds additional custom metadata.",
                    "type": "object",
                    "additionalProperties": true
                },
                "model": {
                    "description": "Model is the model used (for LLM traces).",
                    "type": "string"
                },
                "tokensInput": {
                    "description": "TokensInput is the number of input tokens.",
                    "type": "integer"
                },
                "tokensOutput": {
                    "description": "TokensOutput is the number of output tokens.",
                    "type": "integer"
                },
                "toolInput": {
                    "description": "ToolInput is the input to the tool."
                },
                "toolName": {
                    "description": "ToolName is the name of the tool (for tool traces).",
                    "type": "string"
                },
                "toolOutput": {
                    "description": "ToolOutput is the output from the tool."
                }
            }
        },
        "models.TraceStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "completed",
                "failed"
            ],
            "x-enum-varnames": [
                "TraceStatusPending",
                "TraceStatusRunning",
                "TraceStatusCompleted",
                "TraceStatusFailed"
            ]
        },
        "models.TraceType": {
            "type": "string",
            "enum": [
                "llm",
                "tool",
                "agent",
                "chain",
                "retriever"
            ],
            "x-enum-varnames": [
                "TraceTypeLLM",
                "TraceTypeTool",
                "TraceTypeAgent",
                "TraceTypeChain",
                "TraceTypeRetriever"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer token authentication (MSAL)",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8085",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "UnifiedUI Chat Service API",
	Description:      "Unified abstraction layer for heterogeneous AI agent backends (N8N, Microsoft Foundry, Copilot, LangChain)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
